name: Deploy Masarat App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, bcmath, curl, zip, pdo_pgsql, pgsql, intl, gd, pdo_sqlite, sqlite3
          coverage: none

      - name: Install Composer Dependencies
        run: composer install  --optimize-autoloader

      - name: Run Test Suite
        run: php artisan test --compact

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install NPM & Build React
        run: |
          npm install
          npm run build

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 60s
          command_timeout: 30m
          debug: true
          script: |
            cd /home/user/htdocs/srv1428362.hstgr.cloud
            git pull origin main
            composer install --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            npm install
            npm run build
            php artisan queue:restart || true
